window.LN = window.LN || {};
LN.renderEtsy = () => `<div class="space-y">${LN.header('Etsy','Etsy = ร้านขายไฟล์','ByeTension ลงวอลอาร์ทวันละ 5 listings เวลา 21:30 ไม่ต้องกรอกราย listing ในเว็บ ใช้หน้า Calendar ติ๊กงานพอ')}${LN.externalCard(LN.channelLinks.etsy,'เปิด Etsy ByeTension','ร้านจริง','left-etsy')}<div class="grid grid-3">${LN.mini('เป้าหมาย','5','listings/วัน','left-etsy')}${LN.mini('เวลา','21:30','อัปโหลดทุกวัน','left-etsy')}${LN.mini('Record','Calendar','ติ๊กในหน้าปฏิทิน')}</div>${LN.card('Project Context', `<p class="small text-muted"><b class="strong">ByeTension</b> = ร้านวอลอาร์ท / printable wall art / ใช้ Etsy ขายหลัก และ Pinterest ดันทราฟฟิก ส่วน Life Next Printable Shop ค่อยเปิดเมื่อมีสินค้า 5–10 ชิ้น</p>`)}</div>`;
LN.renderPinterest = () => `<div class="space-y">${LN.header('Pinterest','Pinterest = ป้ายบอกทาง','ลง 3–5 pins ต่อวันเพื่อดัน traffic ไป Etsy/KDP ไม่ต้องกรอกราย pin ตอนนี้')}${LN.externalCard(LN.channelLinks.pinterest,'เปิด Pinterest ByeTension','ช่องจริง','left-pin')}<div class="grid grid-3">${LN.mini('เป้าหมาย','3–5','pins/วัน','left-pin')}${LN.mini('ใช้ภาพ','Reuse','wall art / mockup / preview','left-pin')}${LN.mini('Record','Calendar','ติ๊กในหน้าปฏิทิน')}</div>${LN.card('Project Context', `<p class="small text-muted">Pinterest ใช้กับ ByeTension และ Life Next เป็นสาย search ต้องใช้ภาพอ่านง่ายและ keyword ชัด</p>`)}</div>`;
LN.renderKdp = () => `<div class="space-y">${LN.header('KDP','KDP = สำนักพิมพ์','สมุดเกม planner journal coloring book และ mini guide ระยะยาว ใช้ Product Planner เป็นตัวคุมสถานะ')}${LN.card('Schedule Slots', `<div class="grid grid-3 small"><div class="soft-kdp">KDP Slot 1: วันที่ 14 ของเดือน</div><div class="soft-kdp">KDP Slot 2: วันที่ 28 ของเดือน</div><div class="soft-seasonal">Ebook Slot: วันที่ 21 ของเดือน</div></div>`)}${LN.renderProductRecords()}</div>`;
LN.renderProducts = () => `<div class="space-y">${LN.header('Product Planner','KDP / Planner / Checklist / Ebook','คุมโปรเจกต์ใหญ่ เช่น Cozy Brain Games, Life Next Planner, Life Next Guides และสินค้า Etsy PDF ในอนาคต')}${LN.card('โฟกัสแรก', `<div class="grid grid-4 small"><div class="soft-kdp">Cozy Brain Games</div><div class="soft-kdp">Flower Garden Edition</div><div class="soft-kdp">48–60 หน้า</div><div class="soft-kdp">8.5 x 11 / large print</div></div>`)}${LN.renderProductRecords()}</div>`;
LN.renderSeasonal = () => {
  const current = new Date().getMonth()+1;
  return `<div class="space-y">${LN.header('Seasonal Guide','ไกด์เทศกาล / ธีมรายเดือน','ใช้หาไอเดียให้ถูกฤดูกาล ว่าเดือนไหนควรลงธีมอะไร')}${LN.card('Seasonal Calendar', `<div class="grid grid-3">${LN.seasonalGuide.map(m=>`<div class="season-card ${m.month===current?'current':''}"><div class="season-head"><div class="strong" style="font-size:18px">${m.monthName}</div>${m.month===current?LN.pill('เดือนนี้','soft-seasonal c-seasonal'):''}</div><div class="small c-seasonal strong">${m.theme}</div><div class="tiny text-muted" style="margin-top:8px">${m.ideas}</div></div>`).join('')}</div>`)}</div>`;
};
LN.renderGuide = () => `<div class="space-y">${LN.header('Project Guide','รายละเอียดโครงการทั้งหมด','ดูให้ชัดว่างานแต่ละอย่างเป็นของโปรเจกต์ไหน ลงช่องทางไหน ร้านไหน และทำไปเพื่ออะไร')}${LN.card('Project Map', `<div class="grid grid-3">${LN.projectMap.map(p=>{const c=LN.platformMeta[p.platform]||LN.platformMeta.neutral; return `<div class="season-card ${c.soft}"><div class="strong" style="font-size:18px">${p.project}</div><div class="tiny ${c.color} strong">${p.channels}</div><div class="small strong" style="margin-top:8px">${p.role}</div><div class="tiny text-muted" style="margin-top:8px">${p.whatToDo}</div></div>`}).join('')}</div>`)}</div>`;
LN.renderSettings = () => `<div class="space-y">${LN.header('Settings','ตั้งค่าเว็บ','เวอร์ชันนี้ไม่มี AI ใช้ localStorage บันทึก record ใน browser เครื่องนี้')}${LN.card('สถานะระบบ', `<div class="small text-muted"><p>✅ ไม่มี OpenAI API ในเว็บนี้</p><p>✅ ไม่ต้องตั้งค่า API key</p><p>✅ Facebook / YouTube / Product records บันทึกในเครื่องนี้</p><p>✅ Calendar task done บันทึกในเครื่องนี้</p><p>⚠️ ถ้าล้าง browser data ข้อมูล localStorage จะหาย</p><p>ต่อไปถ้าต้องใช้หลายเครื่อง ค่อยต่อ Supabase</p></div>`)}${LN.card('Backup / Restore JSON', `<div class="backup-box"><button class="btn" id="exportBtn">Export Backup JSON</button><textarea class="textarea" id="backupText" placeholder="กด Export เพื่อคัดลอก backup หรือวาง JSON backup เพื่อ Restore"></textarea><div class="actions"><button class="btn light" id="copyBackup">Copy</button><button class="btn danger" id="restoreBtn">Restore จากช่องด้านบน</button></div><p class="tiny text-muted">แนะนำให้ export เก็บไว้ก่อนล้าง browser หรือย้ายเครื่อง</p></div>`)}</div>`;
LN.bindSettings = () => {
  document.getElementById('exportBtn')?.addEventListener('click',()=>{document.getElementById('backupText').value=LN.exportBackup();});
  document.getElementById('copyBackup')?.addEventListener('click',async()=>{const t=document.getElementById('backupText'); t.select(); try{await navigator.clipboard.writeText(t.value); alert('copy แล้ว');}catch{document.execCommand('copy');}});
  document.getElementById('restoreBtn')?.addEventListener('click',()=>{try{LN.importBackup(document.getElementById('backupText').value); alert('Restore สำเร็จ');}catch(e){alert('JSON ไม่ถูกต้อง / Restore ไม่สำเร็จ');}});
};
