window.LN = window.LN || {};
LN.recordFormValues = (form) => Object.fromEntries(new FormData(form).entries());
LN.renderFacebook = () => {
  const records = LN.loadArray(LN.keys.facebook);
  const ready=records.filter(r=>r.status==='Ready').length, posted=records.filter(r=>r.status==='Posted').length, reuse=records.filter(r=>r.status==='Reuse Later').length;
  const rows = records.map(r=>`<tr><td>${r.date}<div class="sub">${LN.escape(r.theme)}</div></td><td class="pre">${LN.escape(r.caption)}</td><td>${LN.escape(r.imageNote||'')}<div class="sub">${r.link?LN.escape(r.link):''}</div></td><td>${LN.pill(r.status, r.status==='Posted'?'soft-kdp c-kdp':r.status==='Ready'?'soft-fb c-fb':'soft-seasonal c-seasonal')}</td><td><div class="actions">${['Ready','Posted','Reuse Later'].map(s=>`<button class="btn light" data-fb-status="${s}" data-id="${r.id}">${s}</button>`).join('')}<button class="btn danger" data-fb-delete="${r.id}">ลบ</button></div></td></tr>`).join('') || `<tr><td colspan="5" class="empty">ยังไม่มี Facebook record</td></tr>`;
  return `<div class="space-y">${LN.header('Facebook','Facebook = ห้องนั่งเล่น','Project: Life Next Chapter / ลงแคปชั่นพักใจ คนแก่พักใจ slow life และเก็บ record ย้อนหลัง')}${LN.card('วิธีใช้สั้น ๆ', `<div class="grid grid-3 small"><div class="soft-fb">1. ก๊อปแคปชั่นจากที่อื่นมาวาง</div><div class="soft-fb">2. ตั้งสถานะ Ready / Posted</div><div class="soft-fb">3. ถ้า stock ต่ำกว่า 3 วัน ให้สร้างเพิ่ม</div></div>`)}<div class="grid grid-3">${LN.mini('พร้อมลง',ready,`${ready} วัน`,'left-fb')}${LN.mini('ลงแล้ว',posted,'','left-kdp')}${LN.mini('เก็บใช้ซ้ำ',reuse,'','left-seasonal')}</div>${LN.card('เพิ่มแคปชั่น', `<form id="fbForm" class="space-y"><div class="form-row form-3">${LN.input('date',LN.todayISO(),'','date')}${LN.input('theme','','ธีม เช่น คนแก่พักใจ / cozy home')}${LN.select('status',['Ready','Posted','Reuse Later'],'Ready')}</div>${LN.textarea('caption','','วางแคปชั่นตรงนี้')}<div class="form-row" style="grid-template-columns:1fr 1fr 110px">${LN.input('imageNote','','โน้ตรูปภาพ')}${LN.input('link','','ลิงก์โพสต์')}${LN.input('x','','','hidden')}<button class="btn" type="submit">บันทึก</button></div></form>`)}${LN.card('Facebook Records', `<div class="table-wrap"><table><thead><tr><th>วันที่/ธีม</th><th>Caption</th><th>Image/Link</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${rows}</tbody></table></div>`)}</div>`;
};
LN.bindFacebook = () => {
  document.getElementById('fbForm')?.addEventListener('submit', e=>{e.preventDefault(); const v=LN.recordFormValues(e.target); if(!v.caption.trim())return; const records=LN.loadArray(LN.keys.facebook); records.unshift({id:LN.uid(),date:v.date,caption:v.caption,theme:v.theme,imageNote:v.imageNote,link:v.link,status:v.status}); LN.saveArray(LN.keys.facebook,records); LN.navigate('/facebook',false);});
  document.querySelectorAll('[data-fb-status]').forEach(b=>b.onclick=()=>{const records=LN.loadArray(LN.keys.facebook).map(r=>r.id===b.dataset.id?{...r,status:b.dataset.fbStatus}:r);LN.saveArray(LN.keys.facebook,records);LN.navigate('/facebook',false);});
  document.querySelectorAll('[data-fb-delete]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.facebook,LN.loadArray(LN.keys.facebook).filter(r=>r.id!==b.dataset.fbDelete));LN.navigate('/facebook',false);});
};
LN.renderYoutube = () => {
  const records=LN.loadArray(LN.keys.youtube); const ready=records.filter(r=>r.status==='Ready').length, posted=records.filter(r=>r.status==='Posted').length, reels=records.filter(r=>r.reelsDone).length;
  const rows=records.map(r=>`<tr><td>${r.date}<div class="sub">${LN.escape(r.hook||'')}</div></td><td><b>${LN.escape(r.title)}</b><div class="sub pre">${LN.escape(r.details||'')}</div></td><td>${LN.pill(r.status, r.status==='Posted'?'soft-kdp c-kdp':r.status==='Ready'?'soft-yt c-yt':'soft text-muted')}<div style="margin-top:6px">${LN.pill(r.reelsDone?'Reels done':'Reels wait', r.reelsDone?'soft-kdp c-kdp':'soft text-muted')}</div></td><td><div class="sub">${LN.escape(r.youtubeLink||'')}</div></td><td><div class="actions">${['Idea','Ready','Posted'].map(s=>`<button class="btn light" data-yt-status="${s}" data-id="${r.id}">${s}</button>`).join('')}<button class="btn light" data-yt-reels="${r.id}">Reels</button><button class="btn danger" data-yt-delete="${r.id}">ลบ</button></div></td></tr>`).join('') || `<tr><td colspan="5" class="empty">ยังไม่มี YouTube record</td></tr>`;
  return `<div class="space-y">${LN.header('YouTube','YouTube Shorts = เครื่องสร้างอารมณ์','Project: Life Next Chapter / บันทึกคลิป hook รายละเอียด ลิงก์ และติ๊กว่าเอาไปลง Reels แล้วหรือยัง')}${LN.card('วิธีใช้สั้น ๆ', `<div class="grid grid-3 small"><div class="soft-yt">1. บันทึกไอเดียคลิปหรือคลิปพร้อมลง</div><div class="soft-yt">2. ตั้งสถานะ Idea / Ready / Posted</div><div class="soft-yt">3. คลิปที่ Posted แล้วให้ติ๊ก Reels ด้วย</div></div>`)}<div class="grid grid-3">${LN.mini('Ready Shorts',ready,'พร้อมลง','left-yt')}${LN.mini('Posted',posted,'ลง YouTube แล้ว','left-kdp')}${LN.mini('Reels Done',reels,'กระจายไป Reels แล้ว','left-seasonal')}</div>${LN.card('เพิ่มคลิป / ไอเดียคลิป', `<form id="ytForm" class="space-y"><div class="form-row form-4">${LN.input('date',LN.todayISO(),'','date')}${LN.input('title','','ชื่อคลิป / mood')}${LN.input('hook','','Hook / opening text')}${LN.select('status',['Idea','Ready','Posted'],'Idea')}</div>${LN.textarea('details','','รายละเอียดคลิป / shot / music / visual mood')}<div class="form-row" style="grid-template-columns:1fr 130px 110px">${LN.input('youtubeLink','','YouTube link')}<label class="small"><input type="checkbox" name="reelsDone" value="yes"> Reels done</label><button class="btn" type="submit">บันทึก</button></div></form>`)}${LN.card('YouTube Records', `<div class="table-wrap"><table><thead><tr><th>วันที่/Hook</th><th>คลิป</th><th>สถานะ</th><th>Link</th><th>จัดการ</th></tr></thead><tbody>${rows}</tbody></table></div>`)}</div>`;
};
LN.bindYoutube = () => {
  document.getElementById('ytForm')?.addEventListener('submit',e=>{e.preventDefault();const v=LN.recordFormValues(e.target);if(!v.title.trim())return;const records=LN.loadArray(LN.keys.youtube);records.unshift({id:LN.uid(),date:v.date,title:v.title,hook:v.hook,details:v.details,youtubeLink:v.youtubeLink,reelsDone:v.reelsDone==='yes',status:v.status});LN.saveArray(LN.keys.youtube,records);LN.navigate('/youtube',false);});
  document.querySelectorAll('[data-yt-status]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.youtube,LN.loadArray(LN.keys.youtube).map(r=>r.id===b.dataset.id?{...r,status:b.dataset.ytStatus}:r));LN.navigate('/youtube',false);});
  document.querySelectorAll('[data-yt-reels]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.youtube,LN.loadArray(LN.keys.youtube).map(r=>r.id===b.dataset.ytReels?{...r,reelsDone:!r.reelsDone}:r));LN.navigate('/youtube',false);});
  document.querySelectorAll('[data-yt-delete]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.youtube,LN.loadArray(LN.keys.youtube).filter(r=>r.id!==b.dataset.ytDelete));LN.navigate('/youtube',false);});
};
LN.renderProductRecords = () => {
  const records=LN.loadArray(LN.keys.products); const active=records.filter(r=>['Idea','Creating','QA','Ready'].includes(r.status)).length, ready=records.filter(r=>r.status==='Ready').length, published=records.filter(r=>r.status==='Published').length;
  const rows=records.map(r=>`<tr><td><b>${LN.escape(r.project)}</b><div class="sub">${LN.escape(r.platform)}</div></td><td><b>${LN.escape(r.productName)}</b><div class="sub">${LN.escape(r.link||'')}</div></td><td>${LN.escape(r.theme||'')}<div class="sub pre">${LN.escape(r.notes||'')}</div></td><td>${LN.pill(r.status,LN.platformColorClass(r.status))}</td><td><div class="actions">${['Idea','Creating','QA','Ready','Published'].map(s=>`<button class="btn light" data-prod-status="${s}" data-id="${r.id}">${s}</button>`).join('')}<button class="btn danger" data-prod-delete="${r.id}">ลบ</button></div></td></tr>`).join('') || `<tr><td colspan="5" class="empty">ยังไม่มี project record</td></tr>`;
  return `<div class="space-y"><div class="grid grid-3">${LN.mini('Active',active,'','left-product')}${LN.mini('Ready',ready,'','left-seasonal')}${LN.mini('Published',published,'','left-kdp')}</div>${LN.card('เพิ่มโปรเจกต์', `<form id="prodForm" class="space-y"><div class="form-row form-4">${LN.input('date',LN.todayISO(),'','date')}${LN.select('project',['Cozy Brain Games','Life Next Planner','Life Next Guides','ByeTension'],'Cozy Brain Games')}${LN.select('platform',['KDP','Etsy PDF','Etsy ByeTension','Both KDP + Etsy'],'KDP')}${LN.select('status',['Idea','Creating','QA','Ready','Published','Promoted'],'Idea')}</div><div class="form-row form-product">${LN.input('productName','','ชื่อสินค้า / โปรเจกต์')}${LN.input('theme','','Theme')}${LN.input('link','','Link')}</div>${LN.textarea('notes','','Notes / จำนวนหน้า / สิ่งที่ต้องทำต่อ')}<button class="btn" type="submit">บันทึก</button></form>`)}${LN.card('Product Pipeline', `<div class="table-wrap"><table><thead><tr><th>โปรเจกต์</th><th>สินค้า</th><th>Theme/Notes</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>${rows}</tbody></table></div>`)}</div>`;
};
LN.bindProductRecords = () => {
  document.getElementById('prodForm')?.addEventListener('submit',e=>{e.preventDefault();const v=LN.recordFormValues(e.target);if(!v.productName.trim())return;const records=LN.loadArray(LN.keys.products);records.unshift({id:LN.uid(),date:v.date,project:v.project,productName:v.productName,platform:v.platform,theme:v.theme,status:v.status,notes:v.notes,link:v.link});LN.saveArray(LN.keys.products,records);LN.navigate(location.hash.replace('#','')||'/products',false);});
  document.querySelectorAll('[data-prod-status]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.products,LN.loadArray(LN.keys.products).map(r=>r.id===b.dataset.id?{...r,status:b.dataset.prodStatus}:r));LN.navigate(location.hash.replace('#','')||'/products',false);});
  document.querySelectorAll('[data-prod-delete]').forEach(b=>b.onclick=()=>{LN.saveArray(LN.keys.products,LN.loadArray(LN.keys.products).filter(r=>r.id!==b.dataset.prodDelete));LN.navigate(location.hash.replace('#','')||'/products',false);});
};
